# Generated by Django 5.2.6 on 2025-09-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=256, null=True)),
                ('client_timestamp', models.DateTimeField(blank=True, null=True)),
                ('server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=256, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
